# Generated by Django 5.1.6 on 2025-02-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_restaurant_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.CharField(choices=[('option1', '$'), ('option2', '$$'), ('option3', '$$$'), ('option4', '$$$$'), ('option5', '$$$$$')], default='$', max_length=15),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='visit',
            field=models.CharField(choices=[('option1', 'Want to Try'), ('option2', 'Visited')], default='option1', max_length=15),
        ),
    ]
